In [3]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns

In [4]:
df=sns.load_dataset('titanic')

In [5]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [6]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [8]:
df.shape

(891, 15)

In [9]:
df.drop(['class', 'who', 'adult_male', 'deck', 'embark_town','alive'],inplace=True,axis=1)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object
 8   alone     891 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB

In [11]:
df['age']=df['age'].fillna(df['age'].mean())

In [12]:
#drop columns for embarked
df.dropna(subset=['embarked'],inplace=True)

In [13]:
df.shape

(889, 9)

In [14]:
df.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0         0       3    male  22.0      1      0   7.2500        S  False
1         1       1  female  38.0      1      0  71.2833        C  False
2         1       3  female  26.0      0      0   7.9250        S   True
3         1       1  female  35.0      1      0  53.1000        S  False
4         0       3    male  35.0      0      0   8.0500        S   True

In [15]:
df['sibsp'].value_counts()

sibsp
0    606
1    209
2     28
4     18
3     16
8      7
5      5
Name: count, dtype: int64

In [16]:
#label encoding
# df['sex']=df['sex'].map({"male":0,"female":1})

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

df['sex']=le.fit_transform(df['sex'])
df['embarked']=le.fit_transform(df['embarked'])

In [17]:
df['embarked'].value_counts()

embarked
2    644
0    168
1     77
Name: count, dtype: int64

In [18]:
df.head()

   survived  pclass  sex   age  sibsp  parch     fare  embarked  alone
0         0       3    1  22.0      1      0   7.2500         2  False
1         1       1    0  38.0      1      0  71.2833         0  False
2         1       3    0  26.0      0      0   7.9250         2   True
3         1       1    0  35.0      1      0  53.1000         2  False
4         0       3    1  35.0      0      0   8.0500         2   True

In [19]:
df=df.astype(int)
df

     survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0           0       3    1   22      1      0     7         2      0
1           1       1    0   38      1      0    71         0      0
2           1       3    0   26      0      0     7         2      1
3           1       1    0   35      1      0    53         2      0
4           0       3    1   35      0      0     8         2      1
..        ...     ...  ...  ...    ...    ...   ...       ...    ...
886         0       2    1   27      0      0    13         2      1
887         1       1    0   19      0      0    30         2      1
888         0       3    0   29      1      2    23         2      0
889         1       1    1   26      0      0    30         0      1
890         0       3    1   32      0      0     7         1      1

[889 rows x 9 columns]

In [20]:
x=df.drop("survived",axis=1)
y=df['survived']

In [21]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [22]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [23]:
y_pred=model.predict(x_test)
y_pred

array([ 0.09553448,  1.00482818,  0.7993773 ,  0.25304573,  1.03591272,
        0.10159099,  0.28420923,  0.13933958,  0.96247808,  1.01333699,
        0.34259411,  0.65889   , -0.04781761,  0.22899326,  0.08965418,
        0.09817747,  0.43345766,  0.16816687,  0.33443748,  0.08930178,
        0.38852717,  0.99948855,  0.07622298,  0.50952975,  0.08947798,
        0.44097005,  0.29433842,  0.794655  ,  0.43330764,  0.27744793,
        0.43830695,  0.62485456,  0.08947798,  0.46819144, -0.08029625,
        0.42627913,  0.75727739,  0.55759001,  0.16834307,  0.08947798,
        0.15561311,  0.65124771,  0.29667463,  0.10799988,  0.39932496,
        0.44167485,  0.78091794,  0.12046528,  0.22811493,  0.98129713,
        0.92621443,  0.68718156,  0.13293068,  0.20897341,  0.92394914,
        0.82001624,  0.63356739,  0.02697479,  0.17067928,  0.25251713,
        0.43866221,  0.5974187 ,  0.86178873,  0.17067928,  0.76733546,
        0.32783813, -0.04140871,  0.10416823,  0.95772071,  1.04421383,
        0.27174383,  1.08508274,  0.69710248,  0.10194338,  0.58445   ,
        0.71941205,  0.15180498,  0.05190559,  0.8220036 ,  0.43119326,
        0.48569882,  1.00012207,  0.85536414,  0.62485456,  0.27041942,
        0.12873433,  0.00827669,  0.29667463,  0.11423258,  0.08947798,
        0.07683638,  0.62940331,  0.13293068,  0.06437099,  0.09793553,
        0.79990589,  0.08930178,  0.22135363,  0.25035467,  0.12873433,
        0.11423258,  1.11423337,  0.55528729,  0.07077988,  0.05307073,
        0.00222019,  0.59788741,  1.07769447,  0.21179577,  0.13933958,
        0.14574848,  0.6210392 , -0.00922265,  0.93468856,  0.16962923,
        0.16239208,  0.10363713,  0.25698784,  0.58007031,  0.14992047,
        0.4281498 ,  0.93218132, -0.02911951,  0.09053518,  1.1201486 ,
        1.05746921,  0.50952975,  0.91028636,  0.67471616,  0.23727476,
        0.75487006,  0.33977493,  0.22880766,  0.16816687,  0.60412011,
        0.74975444,  0.07683638,  0.78656216,  0.6966386 ,  0.89349044,
        0.69710248,  0.08930178,  0.76163136,  0.48871682,  1.02027449,
        0.38973863,  0.02813993,  1.06751254,  0.08930178,  0.94173064,
        0.12046528,  0.80481684,  0.32288103,  0.47425169,  0.24748987,
        0.85708842,  0.44042134,  0.18740731,  0.12401918,  0.99328206,
        0.15512748,  1.13560938,  0.07060369,  0.12891053,  0.35891341,
        0.59048121,  0.97190856,  0.13293068,  0.05190559,  0.79376724,
        0.78656216,  0.75908427,  0.79488129,  0.16409418,  0.65398171,
        0.39262987,  0.47631671,  0.7473559 ])

In [24]:
y_pred=y_pred.astype(int)
y_pred

array([0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

logical Regression

In [25]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [26]:
accuracy_score(y_test,y_pred)

0.6741573033707865

In [27]:
confusion_matrix(y_test,y_pred)

array([[108,   1],
       [ 57,  12]])

In [28]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.65      0.99      0.79       109
           1       0.92      0.17      0.29        69

    accuracy                           0.67       178
   macro avg       0.79      0.58      0.54       178
weighted avg       0.76      0.67      0.60       178

KNN MODEL

In [29]:
# to use this we should do  feature extraction

In [30]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [31]:
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.fit_transform(x_test)
x_test_scaled

array([[ 0.87837838,  0.83380939, -0.05614186, ..., -0.48065958,
         0.5836712 ,  0.82416338],
       [-1.52702703, -1.19931487, -1.19358508, ...,  1.70666776,
         0.5836712 , -1.21335165],
       [ 0.87837838, -1.19931487, -1.19358508, ..., -0.40323207,
        -1.88998295, -1.21335165],
       ...,
       [ 0.87837838, -1.19931487,  0.75631758, ..., -0.01609448,
         0.5836712 , -1.21335165],
       [ 0.87837838, -1.19931487,  0.35008786, ..., -0.32580455,
         0.5836712 , -1.21335165],
       [ 0.87837838, -1.19931487, -2.00604452, ..., -0.30644767,
         0.5836712 , -1.21335165]], shape=(178, 8))

In [32]:
from sklearn.neighbors import KNeighborsClassifier

In [33]:
knn_model=KNeighborsClassifier(n_neighbors=5)
knn_model.fit(x_train_scaled,y_train)

KNeighborsClassifier()

In [34]:
y_knn = knn_model.predict(x_test_scaled)

In [35]:
accuracy_score(y_test,y_knn)

0.7808988764044944

In [36]:
confusion_matrix(y_test,y_knn)

array([[90, 19],
       [20, 49]])

In [37]:
print(classification_report(y_test,y_knn))

              precision    recall  f1-score   support

           0       0.82      0.83      0.82       109
           1       0.72      0.71      0.72        69

    accuracy                           0.78       178
   macro avg       0.77      0.77      0.77       178
weighted avg       0.78      0.78      0.78       178

Naive Bayes

In [38]:
# here we dont need to use standard scaler

In [39]:
x_train

     pclass  sex  age  sibsp  parch  fare  embarked  alone
708       1    0   22      0      0   151         2      1
240       3    0   29      1      0    14         0      0
382       3    1   32      0      0     7         2      1
792       3    0   29      8      2    69         2      0
683       3    1   14      5      2    46         2      0
..      ...  ...  ...    ...    ...   ...       ...    ...
107       3    1   29      0      0     7         2      1
271       3    1   25      0      0     0         2      1
862       1    0   48      0      0    25         2      1
436       3    0   21      2      2    34         2      0
103       3    1   33      0      0     8         2      1

[711 rows x 8 columns]

In [40]:
from sklearn.naive_bayes import GaussianNB

In [41]:
model_nb=GaussianNB()

In [42]:
model_nb.fit(x_train,y_train)

GaussianNB()

In [43]:
nb_pred=model_nb.predict(x_test)
nb_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [44]:
accuracy_score(y_test,nb_pred)

0.7752808988764045

In [45]:
confusion_matrix(y_test,nb_pred)

array([[84, 25],
       [15, 54]])

In [46]:
print(classification_report(y_test,nb_pred))

              precision    recall  f1-score   support

           0       0.85      0.77      0.81       109
           1       0.68      0.78      0.73        69

    accuracy                           0.78       178
   macro avg       0.77      0.78      0.77       178
weighted avg       0.78      0.78      0.78       178

Decision tree

In [47]:
from sklearn.tree import DecisionTreeClassifier

In [48]:
model_DT= DecisionTreeClassifier(random_state=42)

In [49]:
# in this feature scaling is required 
model_DT.fit(x_train_scaled,y_train)

DecisionTreeClassifier(random_state=42)

In [50]:
pred_DT=model_DT.predict(x_test_scaled)

In [51]:
accuracy_score(y_test,pred_DT)

0.7696629213483146

In [52]:
confusion_matrix(y_test,pred_DT)

array([[88, 21],
       [20, 49]])

In [53]:
print(classification_report(y_test,pred_DT))

              precision    recall  f1-score   support

           0       0.81      0.81      0.81       109
           1       0.70      0.71      0.71        69

    accuracy                           0.77       178
   macro avg       0.76      0.76      0.76       178
weighted avg       0.77      0.77      0.77       178

SVM

In [54]:
from sklearn.svm import SVC

In [55]:
model_svm= SVC(kernel='rbf')

In [56]:
# here alsowe need feature scaling 
model_svm.fit(x_train_scaled,y_train)

SVC()

In [57]:
pred_SVM=model_svm.predict(x_test_scaled)

In [58]:
y_SVC=accuracy_score(y_test,pred_SVM)

In [59]:
confusion_matrix(y_test,pred_SVM)

array([[96, 13],
       [18, 51]])

In [60]:
print(classification_report(y_test,pred_SVM))

              precision    recall  f1-score   support

           0       0.84      0.88      0.86       109
           1       0.80      0.74      0.77        69

    accuracy                           0.83       178
   macro avg       0.82      0.81      0.81       178
weighted avg       0.82      0.83      0.82       178